def common_pods_ios
  inhibit_all_warnings!
  use_frameworks!
  
  pod 'Alamofire', '~> 4.8.2'
end

target 'casumoTestTask' do
   common_pods_ios
end	

target 'casumoTestTaskTests' do
    inherit! :search_paths
    # Pods for testing
end

target 'casumoTestTaskUITests' do
    # Pods for testing
end
